### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by zhaoxin-web** [bespokelabsai/curator#290]
Traceback (most recent call last):
  File "D:\project\python\data_analysis\4.py", line 3, in <module>
    from bespokelabs import curator
  File "D:\develop\Python310\lib\site-packages\bespokelabs\curator\__init__.py", line 2, in <module>
    from .llm.llm import LLM
  File "D:\develop\Python310\lib\site-packages\bespokelabs\curator\llm\llm.py", line 17, in <module>
    from bespokelabs.curator.request_processor.litellm_online_request_processor import (
  File "D:\develop\Python310\lib\site-packages\bespokelabs\curator\request_processor\litellm_online_request_processor.py", line 8, in <module>
    from bespokelabs.curator.request_processor.base_online_request_processor import (
  File "D:\develop\Python310\lib\site-packages\bespokelabs\curator\request_processor\base_online_request_processor.py", line 12, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

What is the reason for this error?

**Comment by zhaoxin-web** [comment]
I have imported the resource package but still get an error

**Comment by madiator** [comment]
Interesting, can you try:
`pip install Resource`
and let us know if that works.

**Comment by RyanMarten** [comment]
@zhaoxin-web What type of system are you on?

**Comment by AK3847** [comment]
Hey I have been getting the same error, this is what I did:

- Made a new venv using `uv venv`
- Installed bespoke-curator using `uv pip install bespokelabs-curator`
- Copied the Quickstart Example 
- Executed it in the same venv using `python test.py`
- On doing `pip show resource` it gives \
  ```bash
   Name: resource
   Version: 0.2.1
   Location: C:\Users\*********\bscurator-uv\.venv\Lib\site-packages
   Requires: jsonform, jsonsir, python-easyconfig
   Required-by:
   ```

I also tried it without uv (although that shouldn't be an issue but gave it a shot anyways) and got the same error.

System - windows11 (home)
Python version - 3.12.7

**Comment by vutrung96** [comment]
@AK3847 @zhaoxin-web it looks like this is due to Windows not supporting the `resource` package:

https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource

**Comment by AK3847** [comment]
So the package can be only run on Unix system for now?

> @AK3847 @zhaoxin-web it looks like this is due to Windows not supporting the `resource` package:
> 
> https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource

**Comment by vutrung96** [comment]
@AK3847 unfortunately yes, we'll prioritize this to support Windows for future release.

of course, feel free to send a PR if you have bandwidth! :)

**Comment by AK3847** [comment]
Thanks and sure I will try to find a workaround.

**Comment by cryptowooser** [comment]
If you really need to use it you can take out the calls to "Resource", they're only in that one file that's throwing the error and otherwise easily removed.
