### ISSUE TITLE
Prevent cache from getting invalid state when ArrowWriter fails

### ISSUE THREAD

**Issue by RyanMarten** [bespokelabsai/curator#51]
Catch exceptions when using Arrow writer and delete the file before raising the exception to the user, so the cache doesn't get into an invalid state (.arrow file is present but not readable).

This results in the following error: 

```
Traceback (most recent call last):
  File "/home/mahesh/code/curator/examples/poem.py", line 84, in <module>
    generate_diverse_poems(how_many=10)
  File "/home/mahesh/code/curator/examples/poem.py", line 76, in generate_diverse_poems
    poems = poet(topics_dataset)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/code/curator/src/bespokelabs/curator/prompter/prompter.py", line 78, in __call__
    return self._completions(self._request_processor, dataset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/code/curator/src/bespokelabs/curator/prompter/prompter.py", line 159, in _completions
    dataset = request_processor.run(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/code/curator/src/bespokelabs/curator/request_processor/openai_online_request_processor.py", line 197, in run
    dataset = self.create_dataset_files(dataset, working_dir, prompt_formatter)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/code/curator/src/bespokelabs/curator/request_processor/base_request_processor.py", line 243, in create_dataset_files
    return Dataset.from_file(dataset_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/.cache/pypoetry/virtualenvs/bespokelabs-curator-tZ21X9LR-py3.11/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 740, in from_file
    table = ArrowReader.read_table(filename, in_memory=in_memory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/.cache/pypoetry/virtualenvs/bespokelabs-curator-tZ21X9LR-py3.11/lib/python3.11/site-packages/datasets/arrow_reader.py", line 329, in read_table
    return table_cls.from_file(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/.cache/pypoetry/virtualenvs/bespokelabs-curator-tZ21X9LR-py3.11/lib/python3.11/site-packages/datasets/table.py", line 1017, in from_file
    table = _memory_mapped_arrow_table_from_file(filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/.cache/pypoetry/virtualenvs/bespokelabs-curator-tZ21X9LR-py3.11/lib/python3.11/site-packages/datasets/table.py", line 63, in _memory_mapped_arrow_table_from_file
    opened_stream = _memory_mapped_record_batch_reader_from_file(filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/.cache/pypoetry/virtualenvs/bespokelabs-curator-tZ21X9LR-py3.11/lib/python3.11/site-packages/datasets/table.py", line 49, in _memory_mapped_record_batch_reader_from_file
    return pa.ipc.open_stream(memory_mapped_stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/.cache/pypoetry/virtualenvs/bespokelabs-curator-tZ21X9LR-py3.11/lib/python3.11/site-packages/pyarrow/ipc.py", line 190, in open_stream
    return RecordBatchStreamReader(source, options=options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahesh/.cache/pypoetry/virtualenvs/bespokelabs-curator-tZ21X9LR-py3.11/lib/python3.11/site-packages/pyarrow/ipc.py", line 52, in __init__
    self._open(source, options=options, memory_pool=memory_pool)
  File "pyarrow/ipc.pxi", line 1006, in pyarrow.lib._RecordBatchStreamReader._open
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Tried reading schema message, was null or length 0
```

This happened since parse_func errored out and  didn't write properly to the dataset file in a previous run and this is trying to read the cached dataset.arrow. 

The solution is then to fix the parse_func bug, but then you get an arrow trying to read the invalid file from the previous run. 

Rather than requiring the user to manually manage the cache (deleting the .arrow file), we should prevent it from getting in this state.

**Comment by RyanMarten** [comment]
catch pyarrow.lib.ArrowInvalid in 
```
bespokelabs/curator/request_processor/base_request_processor.py", line 229, in create_dataset_files
    return Dataset.from_file(dataset_file)
```

**Comment by RyanMarten** [comment]
Related to #40 since the suggested fix when the invalid dataset is detected is to redo `parse_func`. 
However, right now if you change `parse_func` then it will change the hash and won't read from the `responses_0.jsonl`.
 
What is the behavior we want? 
On one hand when `parse_func` is causing errors, you want to fix the error but not re-do the LLM calls. 
On the other hand, you don't want to share cache between two different completions that have two different valid `parse_func`. 

Right now the cache uses the following info: 
```
           [
                str(dataset_hash),
                str(prompt_func_hash),
                str(parse_func_hash),
                str(self.prompt_formatter.model_name),
                str(
                    self.prompt_formatter.response_format.schema_json()
                    if self.prompt_formatter.response_format
                    else "text"
                ),
            ]
```
We can make the name of the arrow file the hash of the `parse_func` so you can have multiple valid `parse_funcs` over the same `requests_0.jsonl` file.
